name: CI

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: its-me/action.zizmor@main
        with:
          config: |
            rules:
              unpinned-uses:
                disable: true
