name: zizmor

on:
  push:
    branches: ['**']
  pull_request:
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: its-me/action.zizmor@v1
        with:
          config: |
            rules:
              artipacked:
                disable: true
              unpinned-uses:
                disable: true
